@proto = http
@host = localhost
@port = 4004


### all BPs
{{proto}}://{{host}}:{{port}}/odata/v4/api-business-partner/BusinessPartnersLocal
?$count=true

### single BP
# @name bp
{{proto}}://{{host}}:{{port}}/odata/v4/api-business-partner/BusinessPartnersLocal
?$filter=BusinessPartner eq '1000034'
# &$select=BusinessPartnerFullName,CreationDate

###### REMOTE
### remote: single BP
{{$dotenv ODATA_URL}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner('1000034')
?$format=json
Authorization: Basic {{$dotenv ODATA_USERNAME}}:{{$dotenv ODATA_USERPWD}}

### get csrf token
# @name csrf
GET {{$dotenv ODATA_URL}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner('LBW-CUST04')
Authorization: Basic {{$dotenv ODATA_USERNAME}}:{{$dotenv ODATA_USERPWD}}
X-CSRF-Token: Fetch

### update
PATCH {{$dotenv ODATA_URL}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner('LBW-CUST04')
Content-Type: application/json
X-CSRF-TOKEN: {{csrf.response.headers.x-csrf-token}}
Authorization: Basic {{$dotenv ODATA_USERNAME}}:{{$dotenv ODATA_USERPWD}}

{
  "FirstName": "Tony",
  "LastName": "Stark"
}

### re-get the entry
GET {{$dotenv ODATA_URL}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner('LBW-CUST04')
?$format=json
Authorization: Basic {{$dotenv ODATA_USERNAME}}:{{$dotenv ODATA_USERPWD}}
